var hous = new Object();
width = document.getElementById("width").value;
length = document.getElementById("length").value;
high = document.getElementById("high").value;
doorsNumber = document.getElementById("doorsNumber").value;
doorsHigh = document.getElementById("doorsHigh").value;
doorsWidth = document.getElementById("doorsWidth").value;
windowsNumber = document.getElementById("windowsNumber").value;
windowsHigh = document.getElementById("windowsHigh").value;
windowsWidth = document.getElementById("windowsWidth").value;
wallThickness = document.getElementById("list").value;
cost = document.getElementById("cost").value;
var area = ((width + length) * 2 * high) - (doorsNumber * doorsHigh * doorsWidth) - (windowsNumber * windowsHigh * windowsWidth);
alert(area);